name: ETL CityBikes

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar ETL
        env:
          API_URL: ${{ secrets.API_URL }}
          OUTPUT_PATH: ${{ secrets.OUTPUT_PATH }}
        run: python ETL.py

      - name: Guardar CSV como artifact
        uses: actions/upload-artifact@v4
        with:
          name: etl-bikes-csv
          path: ${{ env.OUTPUT_PATH }}